# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Elliot-chat-client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        python -m pipenv install --pre --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m pipenv run python -m flake8 app
    - name: Test with pytest
      run: |
        python -m pipenv run python -m pytest tests
